version: "3.8"

services:
  mongo:
    build:
      args:
        - MONGO_PACKAGE=mongodb-enterprise
        - MONGO_REPO=repo.mongodb.com 
    ports:
      - "27017:27017"
      - "27018:27018"
    image: "markchristopherwest/mongo-enterprise:5.0"
    depends_on:
      - vault
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar
  mongosetup:
    build:
      args:
        - MONGO_PACKAGE=mongodb-enterprise
        - MONGO_REPO=repo.mongodb.com 
    image: "markchristopherwest/mongo-enterprise:5.0"
    depends_on:
      - mongo
      - vaultsetup
    restart: "no"
    network_mode: "bridge"
    entrypoint: [ "bash", "-c", "sleep 10 && mongod --enableEncryption --kmipServerName host.docker.internal --kmipPort 5696  --kmipServerCAFile /sensitive/ca.pem --kmipClientCertificateFile /sensitive/client.pem"] 
    volumes:
      - type: bind
        source: ./../sensitive
        target: /sensitive
    
    
  vault:
    ports:
      - "5696:5696"
      - "8200:8200"
      - "8201:8201"
    image: "hashicorp/vault-enterprise:latest"
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - 'VAULT_DEV_ROOT_TOKEN_ID=root'
      - 'VAULT_LICENSE_PATH=/opt/vault/lic/vault.hclic'
      - 'VAULT_SKIP_VERIFY=true'
    volumes:
      - type: bind
        source: ./vault.hcl
        target: /opt/vault/config/vault.hcl
      - type: bind
        source: /tmp/vault.hclic
        target: /opt/vault/lic/vault.hclic
    entrypoint: [ "sh", "-c", "vault server -config /opt/vault/config/vault.hcl -log-level=trace"] 
  vaultsetup:
    expose:
      - "8200"
    image: "ubuntu:22.04"
    depends_on:
      - vault
    # restart: "no"
    network_mode: "bridge"
    entrypoint: [ "sh", "-c", "/sensitive/helper.sh"] 
    volumes:
      - type: bind
        source: ./../terraform
        target: /terraform
      - type: bind
        source: ./../sensitive
        target: /sensitive

